name: "Tran Phuc Hoan"
description: "An Developer with 日本語"

author: "Hoan Tran"
show_downloads: false
google_analytics: UA-93153473-1
permalink: /:year/:month/:day/:slug

github:
  repository_url: https://hoantran.net

theme: jekyll-theme-hacker
