title: "hoantran.name.vn"
author: "Tran Phuc Hoan"
description: "Really cool blog about ... something"
lang: "vi"

# Page settings
permalink: /:year/:month/:day/:slug # see https://jekyllrb.com/docs/permalinks/
date_format: "%B %d, %Y"            # see http://shopify.github.io/liquid/filters/date/
# paginate: 8                         # use "layout: paginate" in the index.html to enable pagination

# Theme settings
hide_title: false   # remove site heading in the header
hide_footer: false  # hide the "previous" and "next" links at the end of each post
dark_theme: true    # use the dark mode as default
dark_header: true   # keep the header dark
dark_footer: true   # keep the footer dark
# style: minimal      # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
  - index.html
  # - README.md
  # - title: "https://"       # linking external sites is also supported

# icons:     # icons in the header, see http://fontawesome.com/icons
# envelope: "mailto:niklasbuschmann@users.noreply.github.com"
# github: "https://github.com/niklasbuschmann/contrast"
# rss: "/contrast/feed.xml"

comments:    # embed disqus or isso comments
  # disqus: "kipalog"
  # isso: ""

google_analytics: UA-93153473-1

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
