title: hoantran.net
name: "Tran Phuc Hoan"
description: "An Developer with 日本語"

author: "Hoan Tran"
show_downloads: false
google_analytics: UA-93153473-1
permalink: /:year/:month/:day/:slug

lang: vi-VN
url: https://hoantran.net

plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/page:num/"

markdown: kramdown
theme: jekyll-theme-hacker
